### ISSUE TITLE
Simply doesn't seem to be working for me on v2.7.6

### ISSUE THREAD

**Issue by richardwiggins** [CodyHouse/cd-lazy-load-changelog#3]
Just added Lazy Load to the bottom gallery on https://mkgeeknight.co.uk/ but looking at Chrome Inspector all the images seem to load straight away.

I'm just using the default settings and v2.7.6.

**Comment by claudia-romano** [comment]
Hi Richard,
the Lazy Load component uses the native [loading attribute](https://caniuse.com/loading-lazy-attr) for browsers that supports it and Chrome is among them. What you see is how Chrome handles the `loading` attribute (the component only sets the proper `src` attribute for each image).

**Comment by richardwiggins** [comment]
Right okay. From what I've ready the loading is very eager but good to know it's working, thanks.
