### ISSUE TITLE
Does lazy loading work with the masonry component?

### ISSUE THREAD

**Issue by jmsobe** [CodyHouse/cd-lazy-load-changelog#4]
Wondering if this will work with the masonry component to lazily load images in this context.

**Comment by jmsobe** [comment]
Here's a followup. I integrated lazy load with masonry but Safari seems to have an issue when the page hasn't fully loaded. You can see the images here outside 
![lightbox-issue-safari](https://user-images.githubusercontent.com/3740448/147134099-f584874f-2462-478f-ad0f-eeed17b1182a.png)
the viewport.

**Comment by claudia-romano** [comment]
Hi there,
you can use lazy loading with masonry if your placeholder image has the same aspect ratio of the final image. Otherwise, masonry won't be able to properly place them. Did you try this way?

**Comment by jmsobe** [comment]
Yes thank you, I changed the placeholder which resolved the issue.
