### ISSUE TITLE
Lazy load not working

### ISSUE THREAD

**Issue by curateship** [CodyHouse/cd-lazy-load-changelog#5]
I've been wanting to use this component for awhile but I don't think it's working even on the codyhouse website. As you can see here https://www.loom.com/share/82c8590a218e42e6a753a589b2fa7720

It just loads all the images.

**Comment by claudia-romano** [comment]
Hi there,
in the video I can see the images loading one after the other while you scroll, as it should be. What do you mean by 'it just loads all the images'? Also, what browser are you using? Thanks!

**Comment by curateship** [comment]
Hmm, I'm not seeing the same thing. When the page loads, all the images definitely all load as once as evidence by the scroll bar here. Also I'm using the brave browser

![image](https://user-images.githubusercontent.com/66774849/157066008-f2a43e04-df87-49fa-845c-a4aad6ef737e.png)

**Comment by claudia-romano** [comment]
If you are using Brave, then it should support the lazy-loading property:
https://caniuse.com/loading-lazy-attr

In this case, there's no JS running but the browser takes care of natively loading the images. Please make sure to check the component info page:
https://codyhouse.co/ds/components/info/lazy-load#img

Cheers!

**Comment by claudia-romano** [comment]
I'm closing this issue as no additional info was provided. Feel free to reopen it if you are still having problems. Cheers!
